// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from "dotenv";
import { defineConfig } from "prisma/config";

// Next.js convention: prefer `.env.local` for local development.
dotenv.config({ path: ".env.local" });
dotenv.config({ path: ".env" });

const DEFAULT_SQLITE_DATABASE_URL = "file:./prisma/dev.db";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: process.env.DATABASE_URL ?? DEFAULT_SQLITE_DATABASE_URL,
  },
});
